databases:
  - name: ai-job-hunter-db
    databaseName: ai_job_hunter
    user: ai_job_hunter_user
    plan: free

services:
  - type: web
    name: ai-job-hunter-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: VITE_API_URL
        value: https://ai-job-hunter-api-cz6k.onrender.com/api
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        value: base64:RNOvvr4z5UCG+9sTTOWnZYvlDVtdnu3DkUU1YQlamUI=
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ai-job-hunter-db
          property: host
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        fromDatabase:
          name: ai-job-hunter-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ai-job-hunter-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ai-job-hunter-db
          property: password